// src/components/LoadingScreen.tsx
import { Progress } from "$/components/ui/progress";
import { cn } from "$/lib/utils";

export type LoadingScreenProps = {
	progress?: number | "full";
	text?: string;
	variant?: "primary" | "success" | "warning" | "error";
};

const defaultProps = {
	progress: 100,
	text: "Loading...",
	variant: "primary",
} satisfies LoadingScreenProps;

export default function LoadingScreen(props: LoadingScreenProps) {
	const { progress, variant, text } = { ...defaultProps, ...props };

	return (
		<div className="flex flex-col gap-0.5">
			<Progress
				value={progress === "full" ? 100 : progress}
				className={cn(
					variant === "primary" && "bg-primary/20 [&>div]:bg-primary",
					variant === "success" && "bg-success/20 [&>div]:bg-success",
					variant === "warning" && "bg-warning/20 [&>div]:bg-warning",
					variant === "error" && "bg-destructive/20 [&>div]:bg-destructive",
				)}
			/>
			<p className={cn(
				"text-left",
				variant === "primary" && "text-primary",
				variant === "error" && "text-destructive",
			)}>
				{text}
			</p>
		</div>
	);
}

// src/lib/components/LoadingScreen.svelte
<script lang="ts">
    import {ProgressBar} from "@skeletonlabs/skeleton";

    export let text = "Loading...";
    export let progress: number | "full" | undefined = undefined;
    export let variant: "primary" | "success" | "warning" | "error" = "primary";

    let meterVariant: string | undefined = undefined;
    let textVariant: string | undefined = undefined;
    $: {
        switch (variant) {
            case "primary":
                meterVariant = "bg-surface-900-50-token";
                textVariant = "text-surface-900-50-token";
                break;
            case "success":
                meterVariant = "bg-success-400-500-token";
                textVariant = "text-success-400-500-token";
                break;
            case "warning":
                meterVariant = "bg-warning-400-500-token";
                textVariant = "text-warning-400-500-token";
                break;
            case "error":
                meterVariant = "bg-error-400-500-token";
                textVariant = "text-error-400-500-token";
                break;
        }
    }
</script>

<div class="flex flex-col gap-0.5">
    <ProgressBar value={progress === "full" ? 100 : progress} meter={meterVariant} />
    <p class="text-left {textVariant}">{text}</p>
</div>
